export default {
    twitter: true,
    og: true,
    copyright: true,
    type: 'website',
    origin: 'https://starsiegeplayers.com/',
    name: 'Starsiege Players',
    siteTags: [
        'download',
        'starsiege',
        'game download',
        'starsiege game download',
        'abandonware',
        'starsiege abandonware',
        'patch',
        'starsiege patch',
        'starsiege multiplayer',
        'starsiege master',
        'starsiege master server',
        'starsiege master server download',
        'starsiege tribes',
        'starsiege universe',
        'starsiege 2845',
        'tribes vengeance',
        'vehicle simulator',
        'mech simulator',
    ],
    siteAuthor: 'Starsiege Players Community',
    siteTwitter: '@starsiegeplayer',
};